[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "G1B1Bowcd3xk9HG3Pq31N98qkUnMwVNtBW6fb5UHyN9v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
